### ISSUE TITLE
Version 3.8 crashes on the start (signal: Aborted)

### ISSUE THREAD

**Issue by ZaWertun** [whoozle/android-file-transfer-linux#226]
System: Fedora 30 x86_64.

There is backtrace:
```c++
Application: android-file-transfer (android-file-transfer), signal: Aborted
Using host libthread_db library "/lib64/libthread_db.so.1".
29	  return SYSCALL_CANCEL (poll, fds, nfds, timeout);
[Current thread is 1 (Thread 0x7f610d1e2840 (LWP 21728))]

Thread 4 (Thread 0x7f60fc8dc700 (LWP 21731)):
#0  __GI___libc_read (nbytes=16, buf=0x7f60fc8dbb30, fd=9) at ../sysdeps/unix/sysv/linux/read.c:26
#1  __GI___libc_read (fd=9, buf=0x7f60fc8dbb30, nbytes=16) at ../sysdeps/unix/sysv/linux/read.c:24
#2  0x00007f6111f1f70f in ?? () from /lib64/libglib-2.0.so.0
#3  0x00007f6111ed7d27 in g_main_context_check () from /lib64/libglib-2.0.so.0
#4  0x00007f6111ed8182 in ?? () from /lib64/libglib-2.0.so.0
#5  0x00007f6111ed8313 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#6  0x00007f611323fbf3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#7  0x00007f61131e99eb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#8  0x00007f6113042635 in QThread::exec() () from /lib64/libQt5Core.so.5
#9  0x00007f6113043786 in ?? () from /lib64/libQt5Core.so.5
#10 0x00007f6112b925a2 in start_thread (arg=<optimized out>) at pthread_create.c:486
#11 0x00007f6112ca8303 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f60fd0f8700 (LWP 21730)):
#0  0x00007f6112c9d5c7 in __GI___poll (fds=0x7f60f0004e30, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f6111ed81de in ?? () from /lib64/libglib-2.0.so.0
#2  0x00007f6111ed8313 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#3  0x00007f611323fbf3 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#4  0x00007f61131e99eb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /lib64/libQt5Core.so.5
#5  0x00007f6113042635 in QThread::exec() () from /lib64/libQt5Core.so.5
#6  0x00007f60fff93f4a in ?? () from /lib64/libQt5DBus.so.5
#7  0x00007f6113043786 in ?? () from /lib64/libQt5Core.so.5
#8  0x00007f6112b925a2 in start_thread (arg=<optimized out>) at pthread_create.c:486
#9  0x00007f6112ca8303 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f60ffdf8700 (LWP 21729)):
#0  0x00007f6112c9d5c7 in __GI___poll (fds=0x7f60ffdf7c68, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f610d23338a in ?? () from /lib64/libxcb.so.1
#2  0x00007f610d234ffa in xcb_wait_for_event () from /lib64/libxcb.so.1
#3  0x00007f61000d5be8 in ?? () from /lib64/libQt5XcbQpa.so.5
#4  0x00007f6113043786 in ?? () from /lib64/libQt5Core.so.5
#5  0x00007f6112b925a2 in start_thread (arg=<optimized out>) at pthread_create.c:486
#6  0x00007f6112ca8303 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f610d1e2840 (LWP 21728)):
[KCrash Handler]
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#7  0x00007f6112bcf895 in __GI_abort () at abort.c:79
#8  0x00007f6112e2a6da in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#9  0x00007f6112e3661c in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#10 0x00007f6112e36677 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57
#11 0x00007f6112e368d9 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x55c360462a00, tinfo=tinfo@entry=0x55c36000c008 <typeinfo for mtp::usb::DeviceBusyException>, dest=dest@entry=0x55c35ffdb6b0 <mtp::usb::DeviceBusyException::~DeviceBusyException()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:95
#12 0x000055c35ffa11aa in mtp::usb::Device::Urb::Submit (this=<optimized out>) at /usr/include/c++/9/ext/new_allocator.h:89
#13 mtp::usb::Device::Submit (this=0x55c360593660, urb=0x7ffc2cdbce00, timeout=<optimized out>) at /usr/src/debug/android-file-transfer-3.8-9.fc30.x86_64/mtp/backend/linux/usb/Device.cpp:262
#14 0x000055c35ffe440d in mtp::usb::Device::ReadBulk (this=0x55c360593660, ep=std::shared_ptr<class mtp::usb::Endpoint> (use count 2, weak count 0) = {...}, outputStream=std::shared_ptr<struct mtp::IObjectOutputStream> (use count 3, weak count 0) = {...}, timeout=timeout@entry=10000) at /usr/src/debug/android-file-transfer-3.8-9.fc30.x86_64/mtp/backend/linux/usb/Device.cpp:328
#15 0x000055c35ffdcf53 in mtp::usb::BulkPipe::Read (this=0x55c36053ccb0, outputStream=std::shared_ptr<struct mtp::IObjectOutputStream> (use count 3, weak count 0) = {...}, timeout=timeout@entry=10000) at /usr/include/c++/9/bits/shared_ptr_base.h:1020
#16 0x000055c35ffc92d8 in mtp::PipePacketer::ReadMessage (this=<optimized out>, outputStream=..., timeout=10000) at /usr/include/c++/9/ext/atomicity.h:96
#17 0x000055c35ffca557 in mtp::PipePacketer::Read (this=0x55c36053cd70, transaction=0, object=std::shared_ptr<struct mtp::IObjectOutputStream> (use count 3, weak count 0) = {...}, code=@0x7ffc2cdbd08e: 0, response=std::vector of length 0, capacity 0, timeout=10000) at /usr/include/c++/9/ext/atomicity.h:96
#18 0x000055c35ffca926 in mtp::PipePacketer::Read (this=this@entry=0x55c36053cd70, transaction=transaction@entry=0, data=std::vector of length 0, capacity 0, code=@0x7ffc2cdbd08e: 0, response=std::vector of length 0, capacity 0, timeout=timeout@entry=10000) at /usr/include/c++/9/ext/atomicity.h:96
#19 0x000055c35ffc4577 in mtp::Device::OpenSession (this=0x55c36053cd70, sessionId=sessionId@entry=1, timeout=timeout@entry=10000) at /usr/src/debug/android-file-transfer-3.8-9.fc30.x86_64/mtp/ptp/Device.cpp:46
#20 0x000055c35ffa69f0 in MainWindow::reconnectToDevice (this=<optimized out>) at /usr/include/c++/9/bits/shared_ptr_base.h:1020
#21 0x000055c35ffa7928 in MainWindow::showEvent (this=0x7ffc2cdbd920) at /usr/src/debug/android-file-transfer-3.8-9.fc30.x86_64/qt/mainwindow.cpp:223
#22 0x00007f6113b8e16e in QWidget::event(QEvent*) () from /lib64/libQt5Widgets.so.5
#23 0x00007f6113ca28f8 in QMainWindow::event(QEvent*) () from /lib64/libQt5Widgets.so.5
#24 0x00007f6113b4baf6 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#25 0x00007f6113b54e80 in QApplication::notify(QObject*, QEvent*) () from /lib64/libQt5Widgets.so.5
#26 0x00007f61131eaae8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /lib64/libQt5Core.so.5
#27 0x00007f6113b8ab17 in QWidgetPrivate::show_helper() () from /lib64/libQt5Widgets.so.5
#28 0x00007f6113b8dc5b in QWidgetPrivate::setVisible(bool) () from /lib64/libQt5Widgets.so.5
#29 0x000055c35ffa3612 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/android-file-transfer-3.8-9.fc30.x86_64/qt/main.cpp:69
[Inferior 1 (process 21728) detached]
```

**Comment by ZaWertun** [comment]
Version 3.7 just freezes for some time and I see this output in the console:
```bash
$ android-file-transfer                                                                                                                                                                                                                                   14.676s (0) 17:52:06
10005 ms since the last poll call
10010 ms since the last poll call
got unknown urb: 0x7ffd274eeb80
10010 ms since the last poll call
```
No crash.

**Comment by whoozle** [comment]
can you test the latest master please?

**Comment by ZaWertun** [comment]
Sure, one moment.

**Comment by ZaWertun** [comment]
Just checked.
Version 3.9 installed from package manager works without crashes.
Version built from master (bee6adb5c50d85c4fd4167b7fc95432f073d9116) works good too.

Maybe there was some packaging issue in version 3.8?
